# Generated by Django 2.2.1 on 2019-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(default='', max_length=150)),
                ('doctor', models.CharField(default='', max_length=150)),
                ('time', models.IntegerField()),
                ('day', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Monday',
        ),
    ]
